spring.application.name=demo
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:./data/mydb
spring.datasource.username=ankushDB
spring.datasource.password=ankush123
spring.jpa.hibernate.ddl-auto=create